<?//begin code admpanel
$id = 15; 
$razdelid = "32"; 
$razdel_id = "32"; 
$razdel_picture = ""; 
$razdel_link = "/perform/academic/index.php"; 
$id_author = 0; 
$title = "Neurofeedback For Your School or School District."; 
$description = "Neurofeedback in schools is good for taxpayers, teachers, students, and parents.  There is no downside. "; 
$partsfragmented = 1; 
$date_posted = "09-12-2003"; 
$linkid = ""; 
$template=1; 
$current_part = 1;
$mainpage = "/home4/jobhuntnow/public_html/alertfocus.com//perform/academic/school.php"; 
$doc_identificate_name = "school"; 
$content_source = ""; 
$content_source_url = ""; 
$url_archive_file = ""; 
//end code admpanel
?><?$site_root="/home4/jobhuntnow/public_html/alertfocus.com/";
include ($site_root."/support/database.php");
$db = connect_db();
$document_template_link = get_document_template_link($db,$template);
$tpl_file = get_tplfiledocument_link($db,$template);
$doc_content =<<<eod
<P align=center><B>Executive Summary – Neurofeedback.</B><B>&nbsp;</B></P>
<P>Imagine wearing a headset and playing a video game that only ‘goes’ when you are learning to increase the brain waves associated with focus and concentration.&nbsp; </P>
<P>Neurofeedback is a kind of biofeedback which uses a sensor and amplifier to detect the brain’s electrical signature so that it can be seen, and thereby controlled.&nbsp; By watching your own neural activity occurring, and gaining control over the brain waves you are producing, you gain greater mental resilience and flexibility. &nbsp;You naturally develop better coordinated neural activity.&nbsp; Multiple and diverse benefits are typical, without any unwanted effects.&nbsp; </P>
<P>The educational benefits apply to all students including athletes, gifted students and those with myriad special needs.&nbsp; Neurofeedback yields permanent improvements in attention, learning, and memory.&nbsp; &nbsp;It is used by the U.S. military, business, athletes and performers to consistently achieve top performance, summon profound concentration, and apply greater mental power to solve complex problems.&nbsp;&nbsp;&nbsp;</P>
<P>There are <B>several hundred </B>scientific studies showing complete and permanent elimination of ADHD, learning problems, and numerous neurological disorders which cripple learning.&nbsp; The process is beneficial for everyone to improve focus and concentration. &nbsp;Over the past 30 years neurofeedback has proven completely safe in all cases.&nbsp; </P>
<P>IQ boosts of 10-20 points are typical in certain special needs groups.&nbsp; No other training or intervention of any kind has so substantially reduced students’ need for pharmaceuticals such as Ritalin.&nbsp; No other technology is as promising to reduce the cost of providing a higher quality education to all students. No remedial or didactic program has such compelling supportive data to fulfill the President’s vision of leaving no student behind. </P>
<P>Several impressive organizations have embraced this technology due it’s extraordinary results.&nbsp; But because the underlying paradigm in new, institutional acceptance and definitive research funding has been slow.&nbsp; The worst that can be said is that more research is warranted.</P>
<P>There are many reasons to get out in front early of this wide open trend thundering at you soon.&nbsp; This may be the first you’ve heard of neurofeedback, but it will not be the last.&nbsp; </P>
<P>A simple investigation on Google using terms such as ‘Neurofeedback, QEEG, Lubar, ADHD, or ‘peak performance’ will be very revealing and convincing of claims made here.&nbsp;&nbsp;</P>
<P align=center><B>The Broad Range of Benefits to Students from Neurofeedback</B></P>
<P><B>Neural Awareness for Mental Self-Regulation. </B><B></B></P>
<P>Biofeedback is learning.&nbsp; Use a special mirror for awareness of a function, and control of that function ensues.&nbsp; It works on the principle that if you can clearly see or hear continuous real-time output of a bodily function such as muscle tension, temperature, or blood pressure, then you can learn to manipulate it.&nbsp; Neurofeedback is biofeedback that uses an EEG to display the weak electrical by-product which all live brains emanate.&nbsp; Some sensors on the scalp can read blood flood in the brain instead of the electrical echo.&nbsp; </P>
<P>Thus, neurofeedback is simply mental activity awareness training.&nbsp; With awareness comes the ability to control brainwave output and opens the possibility for self-regulation.&nbsp; Real time observation of brainwaves leads to improved control for greater resilience and flexibility of well coordinated neural activity.&nbsp; It can look and feel just like playing a videogame with your mind while wearing a special headset.&nbsp; </P>
<P>Neurofeedback has consistently been shown safe and effective in improving self-regulation of neural activity in children of all ages.&nbsp; The benefits are numerous, diverse and profound.&nbsp; The myriad benefits are obtained by all kinds of students.</P>
<P>Of special note, on the one hand, are student athletes and gifted students.&nbsp; The US Army academy and U.S. Olympic program have embraced neurofeedback to optimize peak performance at will.&nbsp;&nbsp;&nbsp;</P>
<P>There is also ample evidence of substantial benefits for those with attention, behavioral, and learning deficits.&nbsp; There is definitive scientific evidence of partial or complete remediation of problems for those with ADHD, learning disorders and myriad neurologically-based disorders.&nbsp; To examine this evidence, simply open a search engine such as Google and enter the terms “Neurofeedback” or “QEEG” and any other term of interest.&nbsp; QEEG stands for Quantitative ElectroEncephaloGraph which is a data intensive brain map used for diagnosis.&nbsp; Caution: There are over 500 high quality scientific journal articles on neurofeedback or EEG biofeedback.&nbsp; </P>
<P>Nearly all students can derive either intellectual, social, emotional, or physiological benefits from optimizing neural functioning through this kind of biofeedback training with an EEG or HEG. </P>
<P>Neurofeedback is safe enough to be approved by the FDA for consumers’ unregulated use.&nbsp; There is no risk in this form of learning.&nbsp; But choices do have to be made, so the training might be supervised by certified professionals, but run day-to-day by teachers’ aids.&nbsp; In competent hands, it is reasonable to expect that 60-90% of all students, will experience permanent educational benefits ranging from subtle to exceptional.&nbsp; </P>
<P>The most likely benefits are enduring increases in the ability to concentrate, focus, learn, remember, and make complex decisions.&nbsp; Many other benefits are commonly reported.&nbsp; For example, IQ increases of 10-20 points are common in certain special needs groups.&nbsp; This result is considered by some to be a combination of remediation of a certain reading or attentional difficulty plus generalized improvement in brain functioning.&nbsp;&nbsp;</P>
<P><B>Quickly Self-Funding, and then Cost Saving. </B></P>
<P>Special education students make disproportionate use of costly resources.&nbsp; The cost of implementing a neurofeedback program is not only small, but it is self-funding.&nbsp; The money to pay for the EEG equipment, software, and trainers are recouped in the cost savings of mainstreaming special education students.&nbsp; This effect will be apparent, even obvious, in any group of students, within a few months of training in school.&nbsp; Even a pilot program should yield net cost savings within one year.&nbsp; </P>
<P>No other kind of method has so substantially reduced students' need for </P>
<P>pharmaceuticals such as Ritalin.&nbsp; No other technology is as promising to enlarge the academic prospects of children with learning handicaps.&nbsp; There is no alternative program, remedial product, or didactic curriculum which can make claims this credible and promising to fulfill the President's vision to leave no child behind.</P>
<P><B>The State of the Art is Continuing to Develop.&nbsp; </B></P>
<P>Neurofeedback is not a new technology.&nbsp; It is not a popular technology.&nbsp; </P>
<P>Longitudinal studies for ADHD are now older than the term ADHD (20 years).&nbsp; The results often show that 90% of students experience complete and permanent relief of attentional symptoms.&nbsp; Enter “Lubar ADHD” in Google.&nbsp;&nbsp;&nbsp;</P>
<P>There are a few theories about how and why it works.&nbsp; But our brains may not be complex enough to understand the complexity of our brains.&nbsp; Compelling to many are the before and after brain maps done with QEEG, SPECT, LORETTA, and other brain imaging techniques.&nbsp; The math and physics are esoteric, but the before and after pictures are obviously more balanced, healthy, and robust.&nbsp; My opinion is that the body will choose health and reject dysfunction when shown how.&nbsp; </P>
<P>Thousands of practitioners all over this nation are performing miracles (according to the Moms) in just 40 sessions.&nbsp; The field is specialized and developing rapidly.&nbsp; Experts are not of one mind on several topics.&nbsp; Advanced and skillful practioners prefer certain equipment, theories and nuances to approaching neurofeedback treatment. &nbsp;There is a lively debate about optimizing training methods.&nbsp; Some seek to reduce the number of sessions while others seek to derive all possible benefits.&nbsp; Several hardware vendors and software technologies claim similar results.</P>
<P>There may not be one ‘best’ approach now.&nbsp; There are not enough well-funded research studies to have settled all these issues.&nbsp; But <B>any of these issues are all minor points </B>when compared with the big picture: massive educational benefits and savings await the willing.&nbsp; Courage and leadership will be rewarded. &nbsp;This is an international opportunity for excellence. </P>
<P><B>How Much Neurofeedback Should We Start … and How Soon? </B></P>
<P>There are three primary issues when considering adoption of any neurofeedback proposal.&nbsp; Safety, effectiveness, and the evaluation process.&nbsp; </P>
<P><B>Safe.&nbsp; </B></P>
<P>When conducted by volunteers or professionals, there is no credible problem with safety.&nbsp; Even in a partially self-insuring district with a litigious population, risk is not an issue.&nbsp; The only real potential litigation problem is NOT adopting neurofeedback in a timely manner, or in rejecting it unfairly.&nbsp; </P>
<P><B>Effective.</B></P>
<P>Hundreds of studies and thousands of testimonials say this is no placebo effect.&nbsp; Despite the evidence of effectiveness, there are not plenty of neurofeedback programs in schools in surrounding districts.&nbsp; The worst that can be said is that neurofeedback is experimental.&nbsp; There are only 500 peer reviewed journal articles with results that range from mild to extraordinary.&nbsp; The big, definitive multi-university, randomized, replicated, double-blind, prospective, controlled scientific study has not yet been funded.&nbsp; We could be a major factor in the coming revolution.&nbsp; This is a highly significant opportunity in all respects.&nbsp; </P>
<P><B>Evaluation.</B></P>
<P>The only expert competent to judge neurofeedback is one familiar with the specific technologies. &nbsp;This kind of proposal has been defeated in other districts because of uniformed and erroneous criticism by experts without expertise.&nbsp; In other districts, it has languished because decision makers had no clear criteria to evaluate degree of effectiveness required for adoption.&nbsp; When a proposal is new or strange, it is subjected to extraordinary levels of fit and proof which apply to no other decision.&nbsp; </P>
<P>In still other districts, those who saw a proposal die, do not say why.&nbsp; Therefore, an open process of evaluation by those qualified in the science and practice of neurofeedback is essential.&nbsp; Reasonable criteria for adoption should be recognized early and then honored in the light of day.&nbsp; The results of fair pilot studies should determine the degree of subsequent steps toward greater use of neurofeedback in the School District. &nbsp;The risk is nil, the upside extraordinary in many ways.&nbsp; </P>
<P>Adopting neurofeedback to any degree requires courage, vision, and openness to good ideas which aren’t entirely understood. &nbsp;The potential rewards are awesome.&nbsp; The risk of inaction is merely unfortunate. </P>
<P>&nbsp;<B>Conclusion:</B></P>
<P>Self-controlled brain wave training has benefits to offer special education students, athletes, gifted students, and all students.&nbsp; There is substantial scientific evidence of complete remediation for those with attention deficits and myriad learning disorders.&nbsp; The largest benefit is for normal students in the form or greater ability to focus on learning.&nbsp;&nbsp;</P>
<P>It is believed that all students can derive either intellectual, social, emotional, or physiological benefits from optimizing neural functioning.&nbsp; There is no risk of harm or downside to this form of learning.&nbsp; In 80-90% of all students, permanent health and educational benefits range from subtle to profound.&nbsp; Most often cited are enduring increases in abilities to concentrate, focus, learn, remember, and make complex decisions.&nbsp; Other benefits such as improvements in sleep are commonly reported.&nbsp; IQ increases of 10-20 points are typical in certain special needs groups.&nbsp; Apart from relieving a deficiency, nothing else increases IQ by 10-20 points.&nbsp; </P>
<P>No other educational program, therapy, or treatment has proven claims to reduce or totally eliminate ADHD students’ need for pharmaceutical stimulants such as Ritalin.&nbsp; No other technology is as promising to reduce the cost of providing a higher quality education to all students. &nbsp;No remedial or didactic program has proven this effective in fulfilling the President’s vision of leaving no student behind.&nbsp;&nbsp;&nbsp;</P>
<P>Beware of expert provincialism, defensiveness, unwarranted caution, and unrevealed economic motives for squelching enlightened forward movement.&nbsp; For example, psychiatry has well funded studies proving drugs are a temporary remedy for ADHD. &nbsp;The drugs don’t work for everyone and there are significant deleterious effects to powerful stimulants.&nbsp; Therapy based on interaction with child psychologists lack the kind of scientific verification for safety or effectiveness enjoyed by neurofeedback.&nbsp; They are naturally in conflict with a technology that can end their usefulness. &nbsp;There are no outspoken critics of neurofeedback who don’t have conflicts of interest, such as livelihood or having received pharmaceutical funding.&nbsp; The entire field of ADHD treatment is due for a paradigm shift.&nbsp; </P>
<P>Every claim in this paper is easily verified with an internet search engine.&nbsp; All the errors and a couple of the opinions are from Gary Ames.&nbsp; I hope you found this introduction useful and that it impels you to rapid, courageous, and dramatic action.</P>
eod;
require $site_root."/".$document_template_link;
@mysql_close($db);
?>