<?//begin code admpanel
$id = 165; 
$razdelid = "37"; 
$razdel_id = "37"; 
$razdel_picture = ""; 
$razdel_link = "/relieve/autism/index.php"; 
$id_author = 0; 
$title = "School-Based Neurofeedback for Autistic Spectrum Disorder"; 
$description = "Mark Darling from Austrailia has conducted an award winning program within a school setting showing a 64% improvement."; 
$partsfragmented = 1; 
$date_posted = "30-04-2008"; 
$linkid = ""; 
$template=1; 
$current_part = 1;
$mainpage = "/home4/jobhuntnow/public_html/alertfocus.com//relieve/autism/austrailia.php"; 
$doc_identificate_name = "austrailia"; 
$content_source = ""; 
$content_source_url = ""; 
$url_archive_file = ""; 
//end code admpanel
?><?$site_root="/home4/jobhuntnow/public_html/alertfocus.com/";
include ($site_root."/support/database.php");
$db = connect_db();
$document_template_link = get_document_template_link($db,$template);
$tpl_file = get_tplfiledocument_link($db,$template);
$doc_content =<<<eod
<B>
<P>School-Based Neurofeedback for Autistic Spectrum Disorder</P></B><I><FONT face=Times-Italic>
<P>By Mark Darling</P></I></FONT><FONT face=Times-Roman size=2>
<P>Mark Darling is a psychologist from Queensland’s Sunshine Coast who specialises in working with children with Autistic Spectrum Disorder and associated developmental and behavioural disorders. He has worked with Disability Services Queensland and served as Paediatric Resource Project Coordinator for Queensland Health. Following a stint as a sole private practitioner, Mark now provides neurotherapy services for Family Challenge, an organisation that provides mental health services in Australia and the developing world, with a particular focus on the rehabilitation of child soldiers in African states. Mark was the recipient of the 2004 Showcase Award for Excellence in Innovation (Education Queensland Regional Winner) and the 2005 Commonwealth Award for Outstanding National Achievement in School Improvement (Federal Dept of Education and Training) for his research in reducing ASD behaviours in the class setting. He is currently pursuing doctoral research into the use of neurotherapy in the education setting.</P></FONT><FONT face=Times-Roman>
<P>Neurofeedback is an intervention that is showing a lot of promise for people diagnosed with Autistic Spectrum Disorder (ASD). While other childhood behaviour disorders such as Attention Deficit Hyperactivity Disorder (ADHD) have been in the neurofeedback limelight for some years, it would appear that ASD is about to have its day in the sun. Recent research is showing that children with ASD are responding very well to both electroencephalographic (EEG) and haemoencephalographic (HEG) neurofeedback. Furthermore, our own research indicates that neurofeedback can be an effective schoolbased intervention for children in the autistic spectrum.</P>
<P>Neurofeedback is an intervention aimed at training individuals to better regulate the biological functioning of their own brain. This has generally involved the self-regulation of EEG rhythmic activity, traditionally referred to as EEG biofeedback, neurofeedback or neurotherapy. In recent years, however, the concept of neurofeedback has expanded to include self-regulation of other neural substrates. For example, haemoencephalography (HEG) is a recently discovered biofeedback technique that encourages improved regional cerebral blood flow. Within a similar timeframe in the mid-1990s, Hershel Toomim invented near infrared haemoencephalography (nir HEG) while Jeff Carmen came up with passive infrared haemoencephalography (pir HEG). Toomim’s device utilises a headband with sensors that measure reflected red and infrared light from brain tissue in order to calculate the degree of oxygenation. Trainees are basically rewarded for increasing red colouration. Carmen’s device employs an infrared thermometer to measure the temperature immediately below the sensor, with trainees being rewarded for increasing core brain temperature. While nir HEG can be used at multiple cortical locations, pir HEG is only used at prefrontal location Fpz. Both methods have been shown to improve metabolism of hypoperfused brain regions.</P><U>
<P>A review of ASD research </P></U>
<P>While many clinicians will be familiar with the scientific literature supporting the use of neurofeedback as a successful intervention for conditions such as epilepsy and ADHD, research into the effectiveness of neurofeedback for the autistic spectrum of disorders is a more recent phenomenon. A couple of case studies were published in the mid-1990s, but it hasn’t been until the new millennium that more rigorous investigations have taken place. Briefly, case studies or case series have included three single case studies of children with autism (Cowan &amp; Markham, 1994; Sichel, Fehmi &amp; Goldstein, 1995; Ibric &amp; Hudspeth, 2003), a series of three children with Autism and Asperger’s Disorder (Thompson &amp; Thompson, 1995), seven children with Asperger’s Syndrome (Ross &amp; Caunt, 2003), 60 individuals with ASD ranging in age from 5 to 51 years (Thompson &amp; Thompson, 2003), and 15 children with Autism and Asperger’s Syndrome (Linden, 2004). All studies reported improved functioning.</P>
<P>In research conducted in Thailand, a series of 181 students with ASD were given 20 sessions of nir HEG in which they were rewarded for increasing cerebral blood flow to the prefrontal cortex of the brain. The result was a Grade Point Average increase of 0.94 on a 4-point scale, as well as a 53% increase in prefrontal blood oxygenation readings (Limsila et al, 2004). Recently, Scolnick (2005) also conducted an EEG biofeedback pilot study with five adolescents with Asperger’s Syndrome that reported mild improvements.</P>
<P>The first controlled group study into the efficacy of neurofeedback for ASD was published in 2002 when an average of 36 neurofeedback sessions were given to a group of 20 children diagnosed with autism. There was also a control group of 20 autistic children who did not receive treatment. Pre- and post-treatment evaluation was in the form of parent reports using the Autism Treatment Evaluation Checklist (ATEC). The experimental group showed an average 26% reduction in autistic symptoms in the areas of communication, social skills, sensory/cognitive awareness, and health and physical behaviours. The control group recorded a 3% reduction in autistic symptoms. (Jerusiewicz, 2002). </P>
<P>In more recent research conducted in New York by Robert Coben’s team, 37 children with ASD were given an average of 20 neurofeedback sessions. A wait list control group of 12 children matched for diagnosis, gender, age, race, handedness, IQ and previous treatments was used. All subjects were assessed using quantitative EEG (QEEG) analysis, infrared imaging, neuropsychological tests and behaviour rating scales. Posttreatment assessment revealed an improvement in 89% of the experimental subjects, with an average 40% reduction in symptoms on the ATEC, as well as significant improvements on neuropsychological tests of attention, language, visual-perception and executive functioning. QEEG and infrared imaging confirmed that positive changes had occurred at a neurophysiological level, particularly in terms of reduced cerebral hyperconnectivity (Coben &amp; Padolsky, 2006).</P>
<P>From the original experimental group of 37 autistic children who completed 20 sessions of neurofeedback, Coben (2006) then took 32 subjects identified as having frontal system dysfunction based on QEEG, infrared imaging, neurobehavioural and neuropsychological testing. The children in the experimental group each received 20 sessions or either nir or pir HEG. Once again a wait list control group of 12 subjects matched for gender, age, race, handedness, IQ and previous treatment was used. Following treatment, 90% of subjects showed improvement, with an average 42% reduction in symptoms on the ATEC. There were also statistically significant improvements on tests of neurobehavioural and neuropsychological functioning, brain thermal imaging and QEEG data. While both forms of HEG provided statistically significant improvements, pir HEG proved more successful than nir HEG on some key measures of functioning.</P>
<P>Finally, Coben &amp; Hudspeth (2006) identified 14 subjects from the previous group who had significant levels of mu wave activity. Mu is an alpha-like rhythm that is associated frontal disconnectivity. Half the group received 20 sessions of frontal bipolar interhemispheric training while the other half received coherence training to increase connectivity between central and prefrontal brain regions. Both groups improved significantly on QEEG, neurobehavioural and neuropsychological measures, but only the coherence trained group demonstrated a reduction in the mu rhythm. Overall, those who completed the three phases of treatment (EEG 1; HEG; EEG 2) averaged an 80% reduction in autistic symptoms.</P><U>
<P>School-based neurofeedback for ASD</P></U>
<P>My own foray into the use of neurofeedback for children in the autistic spectrum began in 1999 with my own son, but soon expanded into general clinical practice. Neurofeedback proved effective, but also very time consuming, since autistic individuals seemed to require longer-term treatment than children with ADHD. Consequently, whenever I presented to educators I challenged them about the potential for neurofeedback as a school-based intervention. The first group to take me up on this challenge was Hervey Bay Special School. Following a further presentation to staff and parents at the school I then provided three days of training for the staff who were selected to be technicians. My main aim was to have them know where to place electrodes, how to get a good signal and how to run a neurofeedback training session.</P>
<P>In 2004 we commenced a pilot project with six autistic students chosen by the school. Each of the students was ascertained as ASD Level 6, the highest level of support required within the Queensland education system. I provided all appropriate assessments on site at the school, and then developed tailor-made neurofeedback protocols for each student. Protocols were e-mailed to the school for downloading onto the neurofeedback computer. Following each session, EEG data and session results were e-mailed back to the clinic for evaluation and protocol adjustment as necessary. Full clinical and technical support was provided and neurotherapy sessions formed part of each child’s Individual Education Profile (IEP). I should point out at this juncture that school neurofeedback technicians were unable to make adjustments to neurofeedback protocols, since we utilised BrainMaster’s remote training system that makes on-site protocol adjustment impossible. This provided a good safeguard since it meant that I was the only person who had the capability of making changes to each student’s protocol.</P>
<P>Students completed an average of 40 neurofeedback sessions in the first semester with improvements on the ATEC ranging from 2% to 47%. One of the main problems with this subjective instrument is that parents and teachers often rated the same child in a completely different light. For example, while one parent rated her son as having improved by only 2%, the school principal acknowledged that he was the student who had probably improved the most. It was later revealed that the parent concerned was personally dealing with a cancer diagnosis at the time she was rating her son’s behaviour, which surely impacted upon her objectivity. Similarly, two teachers were identified early in the process as being opposed to having the neurofeedback program in the school. They seemed somewhat threatened by the new approach and it will come as no surprise that they each regularly rated the students from their classes as showing no improvement, while anecdotal reports from other staff members about the same students were very positive.</P>
<P>Fortunately, the school also established a system of independent direct observation of behaviour in the classroom for each for the students. Pre-determined autistic behaviours were observed and quantified at pre-determined windows of time each day. The result was that across the first 28 neurofeedback sessions, autistic behaviour in the classroom setting reduced by 64% for the students involved in the study. Improvements were also reported in the areas of sleep, mood, speech, academic performance, attention, memory, and social skills; as well as reductions in anger, aggression, seizures, hyperactivity, and impulsivity. The two students who had epilepsy both stopped having seizures, while two non-verbal students both began speaking a few words.</P>
<P>The neurofeedback program at Hervey Bay Special School won a Commonwealth Award for Outstanding National Achievement in School Improvement and was a regional winner of the Courier-Mail Showcase Award for Excellence in Innovation. Subsequently, in 2006 a contract with Education Queensland was established in which I provided training for school staff in a number of regions in Queensland. The aim was to commence neurofeedback programs in a number of schools and start collecting data for my PhD research. Unfortunately, concerns about litigation have led to a suspension of the program by Education Queensland while they do their own literature review into the efficacy and safety of neurofeedback. We can only hope that Education Queensland sees the benefit of neurofeedback as a school-based intervention and that program gets back on track sooner rather than later. In the meantime we continue to provide programs for non-state schools and individuals who attend the clinic.</P></FONT><B>
<P>References</P></B><FONT face=Times-Roman>
<P>Coben, R. (2006). </FONT><I><FONT face=Times-Italic>Hemoencephalography for autistic spectrum disorder</I></FONT><FONT face=Times-Roman>. Presented at the14th Annual Conference of the International Society for Neuronal Regulation, Atlanta, Georgia.</P>
<P>Coben, R. &amp; Hudspeth, W. (2006). </FONT><I><FONT face=Times-Italic>Mu-like rhythms in Autistic spectrum disorder: EEG analyses and neurofeedback. </I></FONT><FONT face=Times-Roman>Presented at the 14th Annual Conference of the International Society for Neuronal Regulation, Atlanta, Georgia.</P>
<P>Coben, R. &amp; Padolsky, I (2006). </FONT><I><FONT face=Times-Italic>Assessment-guided neurofeedback for autistic spectrum disorder. </I></FONT><FONT face=Times-Roman>Manuscript submitted for publication.</P>
<P>Cowan, J. &amp; Markham, L. (1994, March). </FONT><I><FONT face=Times-Italic>EEG biofeedback for the attention problems of autism: A case study</I></FONT><FONT face=Times-Roman>. Presented at the 25th Annual Meeting of the Association for Applied Psychophysiology and Biofeedback. </P>
<P>Ibric, V.L. &amp; Hudspeth, W. (2003). </FONT><I><FONT face=Times-Italic>QEEG and Roshi use in Autism post-toxic encephalopathy – a case study. </I></FONT><FONT face=Times-Roman>Presented at the 11th Annual Winter Brain Conference, Palm Springs, CA.</P>
<P>Jarusiewicz, B. (2002). Efficacy of neurofeedback for children in the autistic spectrum: A pilot study. </FONT><I><FONT face=Times-Italic>Journal of Neurotherapy, 6</I></FONT><FONT face=Times-Roman>(4), 39-49.</P>
<P>Limsila, P., Toomim, H., Kijvithee, J., Bunthong,W., Pookjinda, J., &amp; Utairatanakit, D. (2004). </FONT><I><FONT face=Times-Italic>Hemoencephalography (HEG): An additional treatment for autism</I></FONT><FONT face=Times-Roman>. Retrieved from http://www.biocompresearch.org/Thai_autism_study.htm.</P>
<P>Linden, M. (2004). </FONT><I><FONT face=Times-Italic>Case studies of QEEG mapping and neurofeedback with autism. </I></FONT><FONT face=Times-Roman>Presented at the 12th Annual Conference of the International Society for Neuronal Regulation, Fort Lauderdale, Florida.</P>
<P>Ross, J. &amp; Caunt, J. (2003). </FONT><I><FONT face=Times-Italic>A comparison of QEEG characteristics in pediatric asperger’s syndrome and attention deficit disorder. </I></FONT><FONT face=Times-Roman>Presented at the 11th Annual Conference of the International Society of Neuronal Regulation, Houston, TX. </P>
<P>Scolnick, B. (2005). Effects of electroencephalogram biofeedback with asperger’s syndrome. </FONT><I><FONT face=Times-Italic>International Journal of Rehabilitation Research, 28</I></FONT><FONT face=Times-Roman>(2), 159-163.</P>
<P>Sichel, A.G., Fehmi, L.G., &amp; Goldstein, D.M. (1995). Positive outcome with neurofeedback treatment in a case of mild autism. </FONT><I><FONT face=Times-Italic>Journal of Neurotherapy,1</I></FONT><FONT face=Times-Roman>(1), 60-64.</P>
<P>Thompson, L. &amp; Thompson, M. (1995). </FONT><I><FONT face=Times-Italic>Autism/asperger’s/obnoxious child, 3 case histories: How we get positive results with complex ADD clients</I></FONT><FONT face=Times-Roman>. Presented at the Annual Conference of the Society for Neuronal Regulation.</P>
<P>Thompson, L. &amp; Thompson, M. (2003). </FONT><I><FONT face=Times-Italic>Neurofeedback Treatment for Autistic Spectrum Disorders: Review of 60 Cases-Principles and Outcome</I></FONT><FONT face=Times-Roman>. Citation paper presented at the Proceedings of the Association for Applied Psychophysiology and Biofeedback.</P></FONT>
eod;
require $site_root."/".$document_template_link;
@mysql_close($db);
?>