<?//begin code admpanel
$id = 180; 
$razdelid = "37"; 
$razdel_id = "37"; 
$razdel_picture = ""; 
$razdel_link = "/relieve/autism/index.php"; 
$id_author = 0; 
$title = "Bucks Co. Autism slides"; 
$description = "Text content of PowerPoint slides I presented at Bucks County Autism Conference. "; 
$partsfragmented = 1; 
$date_posted = "27-03-2009"; 
$linkid = ""; 
$template=1; 
$current_part = 1;
$mainpage = "/home4/jobhuntnow/public_html/alertfocus.com//relieve/autism/bucks.php"; 
$doc_identificate_name = "bucks"; 
$content_source = ""; 
$content_source_url = ""; 
$url_archive_file = ""; 
//end code admpanel
?><?$site_root="/home4/jobhuntnow/public_html/alertfocus.com/";
include ($site_root."/support/database.php");
$db = connect_db();
$document_template_link = get_document_template_link($db,$template);
$tpl_file = get_tplfiledocument_link($db,$template);
$doc_content =<<<eod
<H1 style="MARGIN: 0in 0in 0pt"><B><SPAN style="FONT-SIZE: 20pt"><FONT face=Arial>Treat Autism at the Source with Neurofeedback: <BR>Effective, Quick, and Flexible<?xml:namespace prefix = o ns = "urn:schemas-microsoft-com:office:office" /><o:p></o:p></FONT></SPAN></B></H1>
<H1 style="MARGIN: 0in 0in 0pt"><FONT face=Arial></FONT>&nbsp;</H1>
<H1 style="MARGIN: 0in 0in 0pt"><FONT face=Arial>Try My Toys</FONT></H1>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo1"><SPAN style="FONT-SIZE: 14pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 14pt"><FONT face=Arial>Temp.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Hold blue bulb or Hand over sensor.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><o:p></o:p></FONT></SPAN></H2>
<H3 style="MARGIN: 0in 0in 0pt 29.25pt; mso-list: l0 level1 lfo2"><SPAN style="FONT-SIZE: 12pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>–</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial><SPAN style="mso-spacerun: yes">&nbsp;&nbsp;</SPAN><SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN>Prefer higher numbers to find relaxation. <o:p></o:p></FONT></SPAN></H3>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo1"><SPAN style="FONT-SIZE: 14pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 14pt"><FONT face=Arial>EmWave.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Get pulse. Breathe with lights.<o:p></o:p></FONT></SPAN></H2>
<H3 style="MARGIN: 0in 0in 0pt 29.25pt; mso-list: l0 level1 lfo2"><SPAN style="FONT-SIZE: 12pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>–</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial><SPAN style="mso-spacerun: yes">&nbsp;&nbsp;</SPAN>Red &gt; Blue &gt; Green, <o:p></o:p></FONT></SPAN></H3>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo1"><SPAN style="FONT-SIZE: 14pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 14pt"><FONT face=Arial>Stress Eraser.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Make smooth waves.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Triples. <o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo1"><SPAN style="FONT-SIZE: 14pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 14pt"><FONT face=Arial>pRoshi.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Flashing glasses.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><o:p></o:p></FONT></SPAN></H2>
<H3 style="MARGIN: 0in 0in 0pt 29.25pt; mso-list: l0 level1 lfo2"><SPAN><SPAN style="mso-list: Ignore"><FONT face=Arial>–</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp; </SPAN></SPAN><FONT face=Arial>Eyes closed.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN></FONT></SPAN><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial>Adjust round knob.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Flip toggle.<o:p></o:p></FONT></SPAN></H3>
<H3 style="MARGIN: 0in 0in 0pt 29.25pt; mso-list: l0 level1 lfo2"><SPAN style="FONT-SIZE: 12pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>–</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial>Treadmill for the brain. Respond to chaos challenge. </FONT></SPAN></H3>
<H3 style="MARGIN: 0in 0in 0pt 29.25pt; mso-list: l0 level1 lfo2"><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial><o:p></o:p></FONT></SPAN>&nbsp;</H3>
<H1 style="MARGIN: 0in 0in 0pt"><SPAN><FONT face=Arial>Treat autism at the source with neurofeedback: effective, quick, and flexible<o:p></o:p></FONT></SPAN></H1>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo3"><SPAN style="mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><FONT face=Arial>Replicated, controlled research proving substantial treatment effects with neurofeedback.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN></FONT></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo3"><SPAN style="mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><FONT face=Arial>Results have up to p&gt;.001 significance on all measures.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN></FONT></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo3"><SPAN style="mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><FONT face=Arial>They document a 40% reduction in all symptoms across the board. </FONT></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo3"><SPAN style="mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><FONT face=Arial>Success rates are 90%. </FONT></H2>
<P style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo3">&nbsp;</P>
<H1 style="MARGIN: 0in 0in 0pt"><SPAN style="FONT-SIZE: 14pt"><FONT face=Arial>Treat autism at the source with neurofeedback: effective, quick, and flexible<o:p></o:p></FONT></SPAN></H1>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo1"><SPAN style="FONT-SIZE: 14pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 14pt"><FONT face=Arial>Neurofeedback is brain self-training to treat autism at the source. <o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo1"><SPAN style="FONT-SIZE: 14pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 14pt"><FONT face=Arial>Reverse the mechanism of action of a diagnostic marker at the site of the disorder.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo1"><SPAN style="FONT-SIZE: 14pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 14pt"><FONT face=Arial>Broad symptom relief is substantial and permanent and corellated with marker.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo1"><SPAN style="FONT-SIZE: 14pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 14pt"><FONT face=Arial>Pleasant, natural, non-invasive, no drugs, no adverse reactions.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo1"><SPAN style="FONT-SIZE: 14pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 14pt"><FONT face=Arial>Some neurofeedback methods can be used in the home, community and school. </FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo1"><SPAN style="FONT-SIZE: 14pt"><FONT face=Arial><o:p></o:p></FONT></SPAN>&nbsp;</H2>
<H1 style="MARGIN: 0in 0in 0pt"><SPAN style="FONT-SIZE: 14pt"><FONT face=Arial>Treat autism at the source with neurofeedback: effective, quick, and flexible<o:p></o:p></FONT></SPAN></H1>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo4"><SPAN style="FONT-SIZE: 12pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial>What does biofeedback and neurofeedback feel like? <o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo4"><SPAN style="FONT-SIZE: 12pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial>How tightly linked are autistic symptoms and brain wave patterns?<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Hint: r=.87<o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo4"><SPAN style="FONT-SIZE: 12pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial>Learn about various EEG training approaches. <o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo4"><SPAN style="FONT-SIZE: 12pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial>What are the brain wave coherence issues we repair with neurofeedback? <o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo4"><SPAN style="FONT-SIZE: 12pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial>How can you gain biofeedback control over regional cerebral blood flow?<SPAN style="mso-spacerun: yes">&nbsp;&nbsp; </SPAN><o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo4"><SPAN style="FONT-SIZE: 12pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial>Hear about cases of complete remission from autism.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo4"><SPAN style="FONT-SIZE: 12pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial>Get an update on the autism and neurofeedback research. <o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo4"><SPAN style="FONT-SIZE: 12pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial>Discover how easy it is to do training in your office, home or school. <o:p></o:p></FONT></SPAN></H2>
<H1 style="MARGIN: 0in 0in 0pt"><o:p><FONT face=Arial>&nbsp;</FONT></o:p></H1>
<H1 style="MARGIN: 0in 0in 0pt"><SPAN lang=EN-GB style="mso-ansi-language: EN-GB"><FONT face=Arial>Neurofeedback training</FONT></SPAN></H1>
<H1 style="MARGIN: 0in 0in 0pt"><SPAN style="FONT-SIZE: 14pt"><FONT face=Arial>Biofeedback – Neurofeedback – Neurotherapy <o:p></o:p></FONT></SPAN></H1>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo4"><SPAN style="FONT-SIZE: 12pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial>In biofeedback, biological information is fed back to you.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>You look into a behavioral mirror and learn to influence the variations.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Aim, reach, stretch.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>&gt; Range, flexibility. <o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo4"><SPAN style="FONT-SIZE: 12pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial>Neurofeedback feeds back neurological information – EEG or HEG.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Learning, exercise, maturation. <o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo4"><SPAN style="FONT-SIZE: 12pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial>Feedback can be numbers, lights, tones, games, or modulations in any DVD.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo4"><SPAN style="FONT-SIZE: 12pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial>The client just watches their favorite movies which occassionally dims or pause briefly until the brain is working better.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>If you can see it, you can control it.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo4"><SPAN style="FONT-SIZE: 12pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial>Neurotherapy or Neuromodulation is adding energy to the brain: i.e.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo4"><SPAN style="FONT-SIZE: 12pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial>CES (alpha-stim), LENS, Roshi, NeuroField, VNS, rTMS. <o:p></o:p></FONT></SPAN></H2>
<H1 style="MARGIN: 0in 0in 0pt"><o:p><FONT face=Arial>&nbsp;</FONT></o:p></H1>
<H1 style="MARGIN: 0in 0in 0pt"><SPAN style="FONT-SIZE: 20pt"><FONT face=Arial>How is EEG neurofeedback done?<o:p></o:p></FONT></SPAN></H1>
<H1 style="MARGIN: 0in 0in 0pt"><FONT face=Arial>Neurotherapist Screen</FONT></H1>
<H1 style="MARGIN: 0in 0in 0pt"><FONT face=Arial>Brain Wave <BR>Amplitude &amp; Frequency</FONT></H1>
<H1 style="MARGIN: 0in 0in 0pt"><FONT face=Arial>Neurofeedback client screen</FONT></H1>
<H1 style="MARGIN: 0in 0in 0pt"><FONT face=Arial>Brain Self-Regulation</FONT></H1>
<H1 style="MARGIN: 0in 0in 0pt"><FONT face=Arial>Brain Self-Regulation</FONT></H1>
<H1 style="MARGIN: 0in 0in 0pt"><SPAN style="FONT-SIZE: 18pt"><FONT face=Arial>The consious mind is the last to know.<o:p></o:p></FONT></SPAN></H1>
<H1 style="MARGIN: 0in 0in 0pt"><FONT face=Arial>Neuro - factoids<o:p></o:p></FONT></H1>
<H1 style="MARGIN: 0in 0in 0pt"><o:p><FONT face=Arial>&nbsp;</FONT></o:p></H1>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt"><I><SPAN style="FONT-SIZE: 24pt"><FONT face=Arial><SPAN style="mso-tab-count: 1">&nbsp; </SPAN>Electrophysiological studies provide direct support of the "functional<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>underconnectivity" theory of autism.<o:p></o:p></FONT></SPAN></I></H2>
<H1 style="MARGIN: 0in 0in 0pt"><o:p><FONT face=Arial>&nbsp;</FONT></o:p></H1>
<H1 style="MARGIN: 0in 0in 0pt"><FONT face=Arial>Autistic Brains</FONT></H1>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo3"><SPAN style="mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><FONT face=Arial>In autism we see big spikes of intensity in slow brain waves.<SPAN style="mso-spacerun: yes">&nbsp;&nbsp; </SPAN></FONT></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo3"><SPAN style="mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><FONT face=Arial>There are also disturbances in communication between sites within the brain.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN></FONT></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo3"><SPAN style="mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><FONT face=Arial>Hypoconnectivity = hyper independence.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN></FONT></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo3"><SPAN style="mso-fareast-font-family: Arial; mso-bidi-font-weight: bold"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><B><FONT face=Arial>Everybody is shouting; <BR>nobody is listening. <o:p></o:p></FONT></B></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt"><B><o:p><FONT face=Arial>&nbsp;</FONT></o:p></B></H2>
<H1 style="MARGIN: 0in 0in 0pt"><FONT face=Arial>Z-Score training early</FONT></H1>
<H1 style="MARGIN: 0in 0in 0pt"><FONT face=Arial>Z-Score training later</FONT></H1>
<H1 style="MARGIN: 0in 0in 0pt"><SPAN style="FONT-SIZE: 18pt"><FONT face=Arial>2004 Hervey Bay school-based neurofeedback pilot project<o:p></o:p></FONT></SPAN></H1>
<H1 style="MARGIN: 0in 0in 0pt"><o:p><FONT face=Arial>&nbsp;</FONT></o:p></H1>
<H1 style="MARGIN: 0in 0in 0pt"><FONT face=Arial>ASD pilot study</FONT></H1>
<H1 style="MARGIN: 0in 0in 0pt"><SPAN style="FONT-SIZE: 18pt"><FONT face=Arial>Pilot study results: percentage of improvement on ATEC<o:p></o:p></FONT></SPAN></H1>
<H1 style="MARGIN: 0in 0in 0pt"><FONT face=Arial>HEG research</FONT></H1>
<H1 style="MARGIN: 0in 0in 0pt"><FONT face=Arial>Nir HEG research</FONT></H1>
<H1 style="MARGIN: 0in 0in 0pt"><FONT face=Arial>HEG research</FONT></H1>
<H1 style="MARGIN: 0in 0in 0pt"><FONT face=Arial>HEG research - Results</FONT></H1>
<H1 style="MARGIN: 0in 0in 0pt"><FONT face=Arial>EEG research</FONT></H1>
<H1 style="MARGIN: 0in 0in 0pt"><FONT face=Arial>Combined research</FONT></H1>
<H1 style="MARGIN: 0in 0in 0pt"><FONT face=Arial>Case of SL</FONT></H1>
<H1 style="MARGIN: 0in 0in 0pt"><FONT face=Arial>SL - EO Pre and Post</FONT></H1>
<H1 style="MARGIN: 0in 0in 0pt"><FONT face=Arial>SL - EC Pre and Post</FONT></H1>
<H1 style="MARGIN: 0in 0in 0pt"><FONT face=Arial><SPAN style="mso-spacerun: yes">&nbsp;</SPAN>3 Mom’s Report</FONT></H1>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo1"><SPAN style="FONT-SIZE: 14pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 14pt"><FONT face=Arial>Eric went back to school today and his behavior was SOOO CALM!!!<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Eric had 0 incidents of inappropriate touching, 0 tantrums, 0 time outs and went along with everything in school.<o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo1"><SPAN style="FONT-SIZE: 14pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 14pt"><FONT face=Arial>Aaron is a different kid.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>I could cry.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>It’s a miracle.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>He’s excited to go to school.<o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo1"><SPAN style="FONT-SIZE: 14pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 14pt"><FONT face=Arial>Of all the different treatments Susan has received, neurofeedback is the only one that really worked. <o:p></o:p></FONT></SPAN></H2>
<H1 style="MARGIN: 0in 0in 0pt"><SPAN style="FONT-SIZE: 20pt"><FONT face=Arial>Join me.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><BR>Please compete against me.<o:p></o:p></FONT></SPAN></H1>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt"><SPAN style="FONT-SIZE: 10pt"><o:p><FONT face=Arial>&nbsp;</FONT></o:p></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo5"><SPAN style="FONT-SIZE: 10pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 10pt"><FONT face=Arial>Anybody can do biofeedback.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>You need a license to advertise treatment of conditions. <o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo5"><SPAN style="FONT-SIZE: 10pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 10pt"><FONT face=Arial>Educational or theraputic.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Home, school, office. <o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo5"><SPAN style="FONT-SIZE: 10pt; mso-fareast-font-family: Arial; mso-bidi-font-weight: bold"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 10pt"><FONT face=Arial>Costs $1800 - $10,000 to get up and running.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Learning curve varies widely depending on system.<SPAN style="mso-spacerun: yes">&nbsp;&nbsp; </SPAN><BR style="mso-special-character: line-break"><BR style="mso-special-character: line-break"><o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo5"><SPAN><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><FONT face=Arial>ISNR.org </FONT></SPAN><SPAN style="FONT-SIZE: 10pt"><FONT face=Arial><SPAN style="mso-spacerun: yes">&nbsp;</SPAN>International Society of Neurofeedback and Research<o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo5"><SPAN><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><FONT face=Arial>AAPB.org</FONT></SPAN><SPAN style="FONT-SIZE: 10pt"><FONT face=Arial> Association for Applied Psychophysiology and Biofeedback<o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo5"><SPAN><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><FONT face=Arial>NRBS.org</FONT></SPAN><SPAN style="FONT-SIZE: 10pt"><FONT face=Arial> NorthEast Regional Biofeedback Society<o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo5"><SPAN><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><FONT face=Arial>PABiofeedback.org</FONT></SPAN><SPAN style="FONT-SIZE: 10pt"><FONT face=Arial> Pennsylvania Society for Biofeedback and Behavioral Medicine. <o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo5"><SPAN style="FONT-SIZE: 10pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 10pt"><FONT face=Arial>Yahoo groups.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>News groups – email club.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Search neurofeedback.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><o:p></o:p></FONT></SPAN></H2>
<H1 style="MARGIN: 0in 0in 0pt"><SPAN style="FONT-SIZE: 20pt"><FONT face=Arial>Join me.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><BR>Please compete against me.<o:p></o:p></FONT></SPAN></H1>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo4"><SPAN style="FONT-SIZE: 12pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><A href="http://www.pocket-neurobics.com/"><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial>www.pocket-neurobics.com</FONT></SPAN></A><SPAN style="FONT-SIZE: 12pt"><BR><FONT face=Arial><SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN>stand alone, PC or wireless. <o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo4"><SPAN style="FONT-SIZE: 12pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><A href="http://www.brainmaster.com/"><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial>www.BrainMaster.com</FONT></SPAN></A><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial>, Diverse options, Z-Score. <o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo4"><SPAN style="FONT-SIZE: 12pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><A href="http://www.zengar.com/"><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial>www.zengar.com</FONT></SPAN></A><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial> – NeuroCARE – NeurOptimal.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo4"><SPAN style="FONT-SIZE: 12pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><A href="http://www.smartbraingames.com/"><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial>www.SmartBrainGames.com</FONT></SPAN></A><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial> uses Nintendo or X-Box.<o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo4"><SPAN style="FONT-SIZE: 12pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><A href="http://www.playattention.com/"><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial>www.PlayAttention.com</FONT></SPAN></A><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial>—single channel, helmet <o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo4"><SPAN style="FONT-SIZE: 12pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><A href="http://www.bio–medical.com/"><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial>www.bio–medical.com</FONT></SPAN></A><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial> Various.<o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo4"><SPAN style="FONT-SIZE: 12pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial>Others: Stens, ThoughTechnology<o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo4"><SPAN style="FONT-SIZE: 12pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial>QEEG <o:p></o:p></FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt"><SPAN style="FONT-SIZE: 12pt"><o:p><FONT face=Arial>&nbsp;</FONT></o:p></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo4"><SPAN style="FONT-SIZE: 12pt; mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial>·<SPAN style="mso-spacerun: yes">&nbsp; </SPAN></FONT></SPAN><A href="http://www.ochslabs.com/"><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial>www.OchsLabs.com</FONT></SPAN></A><SPAN style="FONT-SIZE: 12pt"><FONT face=Arial> LENS<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Low Energy NF System. <o:p></o:p></FONT></SPAN></H2>
<H1 style="MARGIN: 0in 0in 0pt"><SPAN style="FONT-SIZE: 20pt"><FONT face=Arial>Healing Gadgets<BR>Entry level biofeedback<o:p></o:p></FONT></SPAN></H1>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo3"><SPAN style="mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><FONT face=Arial>Stress Thermometer – Temp.</FONT></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo3"><SPAN style="mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><A href="http://www.wilddivine.com/"><FONT face=Arial>www.WildDivine.com</FONT></A><FONT face=Arial><SPAN style="mso-spacerun: yes">&nbsp; </SPAN>GSR &amp; HRV</FONT></H2>
<H3 style="MARGIN: 0in 0in 0pt 29.25pt; mso-list: l0 level1 lfo6"><SPAN style="mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial size=5>–</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp; </SPAN></SPAN></SPAN><A href="http://www.somaticvision.com/"><FONT face=Arial size=5>www.SomaticVision.com</FONT></A><FONT face=Arial size=5> GSR &amp; HRV</FONT></H3>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo3"><SPAN style="mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><A href="http://www.heartmath.com/"><FONT face=Arial>www.HeartMath.com</FONT></A><FONT face=Arial> HRV</FONT></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo3"><SPAN style="mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><A href="http://www.stresseraser.com/"><FONT face=Arial>www.StressEraser.com</FONT></A><FONT face=Arial> HRV</FONT></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo3"><SPAN style="mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><A href="http://www.alpha-stim.com/"><FONT face=Arial>www.Alpha-Stim.com</FONT></A><FONT face=Arial><SPAN style="mso-spacerun: yes">&nbsp;&nbsp; </SPAN>CES <SPAN style="mso-tab-count: 1"></SPAN></FONT><A href="http://www.healthpax.com/"><FONT face=Arial>www.HealthPax.com</FONT></A><SPAN style="mso-spacerun: yes"><FONT face=Arial>&nbsp; </FONT></SPAN></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo3"><SPAN style="mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><FONT face=Arial>E-Z Air </FONT><A href="http://www.bfe.org/"><FONT face=Arial>www.BFE.org</FONT></A><FONT face=Arial> Free breath pacer.</FONT></H2>
<H1 style="MARGIN: 0in 0in 0pt"><o:p><FONT face=Arial>&nbsp;</FONT></o:p></H1>
<H1 style="MARGIN: 0in 0in 0pt"><FONT face=Arial>Heart Rate Variability</FONT></H1>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo3"><SPAN style="mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><FONT face=Arial>Tic-toc &#8800; Lub-dub<SPAN style="mso-spacerun: yes">&nbsp;&nbsp; </SPAN>RSA</FONT></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo3"><SPAN style="mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><FONT face=Arial>HRV is well established marker for health and well-being. </FONT></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo3"><SPAN style="mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><FONT face=Arial>3 ways to maximize HRV now. </FONT></H2>
<H3 style="MARGIN: 0in 0in 0pt 29.25pt; mso-list: l0 level1 lfo6"><SPAN style="mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial size=5>–</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp; </SPAN></SPAN></SPAN><FONT face=Arial size=5>Breath pacer, biofeedback, feel the love.</FONT></H3>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo3"><SPAN style="mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><FONT face=Arial>A resonance frequency in the body where heart rate occilations are in coherent phase with breathing rhythm.</FONT></H2>
<H1 style="MARGIN: 0in 0in 0pt"><o:p><FONT face=Arial>&nbsp;</FONT></o:p></H1>
<H1 style="MARGIN: 0in 0in 0pt"><FONT face=Arial>Builds Stress Resilience</FONT></H1>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo3"><SPAN style="mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><FONT face=Arial>More harmonious relations at work.</FONT></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo3"><SPAN style="mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><FONT face=Arial>Athletes win more games.</FONT></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo3"><SPAN style="mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><FONT face=Arial>Performing artists do better on stage.</FONT></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo3"><SPAN style="mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><FONT face=Arial>Students do better on stressful tests.</FONT></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo3"><SPAN style="mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><FONT face=Arial>Police can run fast and then shoot straight.</FONT></H2>
<H2 style="MARGIN: 0in 0in 0pt 13.5pt; mso-list: l0 level1 lfo3"><SPAN style="mso-fareast-font-family: Arial"><SPAN style="mso-list: Ignore"><FONT face=Arial>•</FONT><SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><FONT face=Arial>High blood pressure normalizes.</FONT></H2>
<H1 style="MARGIN: 0in 0in 0pt"><FONT face=Arial>Calm CNS</FONT></H1>
<H1 style="MARGIN: 0in 0in 0pt"><SPAN style="FONT-SIZE: 20pt"><FONT face=Arial>Treat Autism at the Source with Neurofeedback: <BR>Effective, Quick, and Flexible</FONT></SPAN></H1>
<H1 style="MARGIN: 0in 0in 0pt"><SPAN style="FONT-SIZE: 20pt"><FONT face=Arial>&nbsp;
<DIV class=O v:shape="_x0000_s1026">
<DIV style="mso-char-wrap: 1; mso-kinsoku-overflow: 1"></DIV>
<DIV style="mso-char-wrap: 1; mso-kinsoku-overflow: 1"><B>Gary Ames</B>, MA, MBA.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Licensed psychologist. </DIV>
<DIV style="mso-char-wrap: 1; mso-kinsoku-overflow: 1">Private practice specializing in neurofeedback since 2003. </DIV>
<DIV style="mso-char-wrap: 1; mso-kinsoku-overflow: 1">ADHD, anxiety, autism, depression, insomnia, migraine, seizures, TBI, etc. </DIV>
<DIV style="mso-char-wrap: 1; mso-kinsoku-overflow: 1"><B>“My clients get off meds”</B>. </DIV>
<DIV style="mso-char-wrap: 1; mso-kinsoku-overflow: 1">Executive Director, Behavior Analysis &amp; Therapy, BHRS in Montgomery County and MH agency. </DIV>
<DIV style="mso-char-wrap: 1; mso-kinsoku-overflow: 1"></DIV>
<DIV style="mso-char-wrap: 1; mso-kinsoku-overflow: 1"><SPAN style="WIDTH: 10.57%; mso-tab-count: 1"></SPAN>Gary Ames </DIV>
<DIV style="mso-char-wrap: 1; mso-kinsoku-overflow: 1"><SPAN style="WIDTH: 10.57%; mso-tab-count: 1"></SPAN>AlertFocus.com </DIV>
<DIV style="mso-char-wrap: 1; mso-kinsoku-overflow: 1"><SPAN style="WIDTH: 10.57%; mso-tab-count: 1"></SPAN>28 Rock Hill Road, Bala Cynwyd, PA 19004 </DIV>
<DIV style="mso-char-wrap: 1; mso-kinsoku-overflow: 1"><SPAN style="WIDTH: 10.57%; mso-tab-count: 1"></SPAN>610.668-3223, Gary Ames@AlertFocus.com </DIV>
<DIV style="mso-char-wrap: 1; mso-kinsoku-overflow: 1; mso-line-spacing: '100 50 0'"></DIV></DIV><o:p></o:p></FONT></SPAN></H1>
eod;
require $site_root."/".$document_template_link;
@mysql_close($db);
?>