<?//begin code admpanel
$id = 120; 
$razdelid = "28"; 
$razdel_id = "28"; 
$razdel_picture = ""; 
$razdel_link = "/relieve/stress/index.php"; 
$id_author = 0; 
$title = "Zone"; 
$description = "Biofeedback with Alert Focus puts you In The Zone.  Health, performance, and productivity follow naturally.
"; 
$partsfragmented = 1; 
$date_posted = "15-06-2005"; 
$linkid = ""; 
$template=1; 
$current_part = 1;
$mainpage = "/home4/jobhuntnow/public_html/alertfocus.com//relieve/stress/zone.php"; 
$doc_identificate_name = "zone"; 
$content_source = ""; 
$content_source_url = ""; 
$url_archive_file = ""; 
//end code admpanel
?><?$site_root="/home4/jobhuntnow/public_html/alertfocus.com/";
include ($site_root."/support/database.php");
$db = connect_db();
$document_template_link = get_document_template_link($db,$template);
$tpl_file = get_tplfiledocument_link($db,$template);
$doc_content =<<<eod
<P style="MARGIN: 0in 0in 6pt"><STRONG><SPAN style="FONT-WEIGHT: normal; COLOR: black; FONT-FAMILY: Arial; mso-bidi-font-weight: bold"><FONT size=3>Alert Focus combines biofeedback awareness training and coaching to help you overcome the stress of change and uncertainty.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>We make it easy to learn how to improve personal health and performance for greater workplace productivity.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><?xml:namespace prefix = o ns = "urn:schemas-microsoft-com:office:office" /><o:p></o:p></FONT></SPAN></STRONG></P>
<P style="MARGIN: 0in 0in 6pt"><STRONG><SPAN style="FONT-WEIGHT: normal; COLOR: black; FONT-FAMILY: Arial; mso-bidi-font-weight: bold"><FONT size=3>Alert Focus gets you In The Zone – a state of optimum performance.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>In The Zone is feeling ease, energy, and with ample capability.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><o:p></o:p></FONT></SPAN></STRONG></P>
<P style="MARGIN: 0in 0in 6pt"><FONT size=3><STRONG><SPAN style="FONT-WEIGHT: normal; COLOR: black; FONT-FAMILY: Arial; mso-bidi-font-weight: bold">We come to you for biofeedback </SPAN></STRONG><STRONG><SPAN style="FONT-WEIGHT: normal; COLOR: black; mso-bidi-font-weight: bold"><FONT face="Times New Roman">awareness</FONT></SPAN></STRONG><STRONG><SPAN style="FONT-WEIGHT: normal; COLOR: black; FONT-FAMILY: Arial; mso-bidi-font-weight: bold"> and training sessions.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>We guide you in person and on the phone to apply your learning.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>We work with you to direct your increased capacity toward business goals.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>You keep the lasting benefits by living In The Zone.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><SPAN style="mso-spacerun: yes">&nbsp;</SPAN><o:p></o:p></SPAN></STRONG></FONT></P>
<P style="MARGIN: 0in 0in 6pt"><FONT size=3><STRONG><SPAN style="FONT-WEIGHT: normal; COLOR: black; FONT-FAMILY: Arial; mso-bidi-font-weight: bold">Everyone can learn how to ‘be at your best’ nearly all the time.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>The process is quick (</SPAN></STRONG><STRONG><SPAN style="FONT-WEIGHT: normal; COLOR: black; mso-bidi-font-weight: bold"><FONT face="Times New Roman">several</FONT></SPAN></STRONG><STRONG><SPAN style="FONT-WEIGHT: normal; COLOR: black; FONT-FAMILY: Arial; mso-bidi-font-weight: bold"> sessions plus homework), cheap (several options), and easy (sit and concentrate on the feedback).<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Anyone can improve work performance, health, and quality of life.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>The strongest economic benefits go to those in a </SPAN></STRONG><STRONG><SPAN style="FONT-WEIGHT: normal; COLOR: black; mso-bidi-font-weight: bold"><FONT face="Times New Roman">position</FONT></SPAN></STRONG><STRONG><SPAN style="FONT-WEIGHT: normal; COLOR: black; FONT-FAMILY: Arial; mso-bidi-font-weight: bold"> to make the largest business impact.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><o:p></o:p></SPAN></STRONG></FONT></P>
<P style="MARGIN: 0in 0in 6pt"><STRONG><SPAN style="COLOR: black; FONT-FAMILY: Arial"><FONT size=3>How it works<o:p></o:p></FONT></SPAN></STRONG></P>
<P style="MARGIN: 0in 0in 6pt"><STRONG><SPAN style="FONT-WEIGHT: normal; COLOR: black; FONT-FAMILY: Arial; mso-bidi-font-weight: bold"><FONT size=3>We use training and biofeedback to provide self-awareness.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Improved awareness of inner states promotes self-regulation.<SPAN style="mso-spacerun: yes">&nbsp;&nbsp; </SPAN>First we show you The Zone.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Gradually you learn how to stay there.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Soon you are working at your best, without strain, and doing all aspects of you life with greater calm, energy, and assurance.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Success naturally follows.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><o:p></o:p></FONT></SPAN></STRONG></P>
<P style="MARGIN: 0in 0in 6pt"><STRONG><SPAN style="FONT-WEIGHT: normal; COLOR: black; FONT-FAMILY: Arial; mso-bidi-font-weight: bold"><FONT size=3>Our easy-to-use training solutions boost and sustain health.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Both performance and productivity go up.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>The improvements are typically dramatic.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>They are long <SPAN style="mso-spacerun: yes">&nbsp;</SPAN>lasting because awareness and self-regulation means self-correcting.<o:p></o:p></FONT></SPAN></STRONG></P>
<P style="MARGIN: 0in 0in 6pt"><STRONG><SPAN style="FONT-WEIGHT: normal; COLOR: black; FONT-FAMILY: Arial; mso-bidi-font-weight: bold"><FONT size=3>As you become skilled at regulating your own emotions, skill with people always increases.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Awareness and skill with your own feelings and with other people is called emotional intelligence. <o:p></o:p></FONT></SPAN></STRONG></P>
<P style="MARGIN: 0in 0in 6pt"><STRONG><SPAN style="FONT-WEIGHT: normal; COLOR: black; FONT-FAMILY: Arial; mso-bidi-font-weight: bold"><FONT size=3>Obtaining this degree of benefit is safe and described as interesting or pleasant.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>You just watch your heartbeat and learn to produce more regular rhythms.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>As your heartbeats rhythm becomes more steady, all kinds of wonderful things happen to your health, mind, and emotions.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>There is ample scientific research.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><o:p></o:p></FONT></SPAN></STRONG></P>
<P style="MARGIN: 0in 0in 6pt"><STRONG><SPAN style="FONT-WEIGHT: normal; COLOR: black; FONT-FAMILY: Arial; mso-bidi-font-weight: bold"><FONT size=3>A more regular heartbeat is coherent.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>A coherent heart beat sends a pure message that your brain follows.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Soon your heart and head are in sync and moving together toward harmony.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>It really is that simple, if you can watch and learn with Alert Focus biofeedback.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><o:p></o:p></FONT></SPAN></STRONG></P>
<P style="MARGIN: 0in 0in 6pt"><STRONG><SPAN style="FONT-WEIGHT: normal; COLOR: black; FONT-FAMILY: Arial; mso-bidi-font-weight: bold"><FONT size=3>We offer clean and clear procedures, no mumbo-jumbo.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>We read your dynamic heart rate and show you the patterns you are producing now.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>We give you a target for optimal heart rate variability and you feel the benefits within minutes or in a couple of sessions.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><o:p></o:p></FONT></SPAN></STRONG></P>
<P style="MARGIN: 0in 0in 6pt"><STRONG><SPAN style="FONT-WEIGHT: normal; COLOR: black; FONT-FAMILY: Arial; mso-bidi-font-weight: bold"><FONT size=3>The benefits will be obvious.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>You can tell that something good and right is occurring.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Increased heart-body-mind synchrony and coherence are clearly preferred.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><o:p></o:p></FONT></SPAN></STRONG></P>
<P style="MARGIN: 0in 0in 6pt"><STRONG><SPAN style="FONT-WEIGHT: normal; COLOR: black; FONT-FAMILY: Arial; mso-bidi-font-weight: bold"><FONT size=3>You may not know that you are balancing the sympathetic and parasympathetic parts of your autonomic nervous system, but you will feel the benefits.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><o:p></o:p></FONT></SPAN></STRONG></P>
<P><FONT size=3><STRONG><SPAN style="COLOR: black; FONT-FAMILY: Arial">Focus and Attention Building with Computer Assisted Training</SPAN></STRONG><STRONG><SPAN style="FONT-WEIGHT: normal; COLOR: black; FONT-FAMILY: Arial; mso-bidi-font-weight: bold">.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><o:p></o:p></SPAN></STRONG></FONT></P>
<P><STRONG><SPAN style="FONT-WEIGHT: normal; COLOR: black; FONT-FAMILY: Arial; mso-bidi-font-weight: bold"><FONT size=3>Yes, greater mental focus can be achieved by everyone with biofeedback.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><o:p></o:p></FONT></SPAN></STRONG></P>
<P><STRONG><SPAN style="FONT-WEIGHT: normal; COLOR: black; FONT-FAMILY: Arial; mso-bidi-font-weight: bold"><FONT size=3>This is another kind of biofeedback to safely bring your central nervous system in sync.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>With enough sessions of this biofeedback training, 75 to 90% of clients say they have greater concentration, memory, creativity.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>They report improved capacity to learn and solve complex problems.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Health and emotional intelligence benefits are common. <o:p></o:p></FONT></SPAN></STRONG></P>
eod;
require $site_root."/".$document_template_link;
@mysql_close($db);
?>