<?//begin code admpanel
$id = 182; 
$razdelid = "34"; 
$razdel_id = "34"; 
$razdel_picture = ""; 
$razdel_link = "/relieve/add/index.php"; 
$id_author = 0; 
$title = "Efficacy of Neurofeedback Treatment in ADHD"; 
$description = "Link to Meta-Analysis showing strong effect size for neurofeedback."; 
$partsfragmented = 1; 
$date_posted = "26-07-2009"; 
$linkid = ""; 
$template=1; 
$current_part = 1;
$mainpage = "/home4/jobhuntnow/public_html/alertfocus.com//relieve/add/meta.php"; 
$doc_identificate_name = "meta"; 
$content_source = ""; 
$content_source_url = ""; 
$url_archive_file = ""; 
//end code admpanel
?><?$site_root="/home4/jobhuntnow/public_html/alertfocus.com/";
include ($site_root."/support/database.php");
$db = connect_db();
$document_template_link = get_document_template_link($db,$template);
$tpl_file = get_tplfiledocument_link($db,$template);
$doc_content =<<<eod
<P>Clinical EEG and Neuroscience. 2009 Vol. 40 No. 3</P>
<P><A href="http://eegbulletinboard.com/groupee_files/attachments/4/4/5/445102302/445102302_ECNS_Arns_prf.pdf?ts=4A649D1A&amp;key=C5081747CE4E8F2F332A3BA00634C30A&amp;referrer=http%3A%2F%2Feegbulletinboard.com%2Feve%2Fforums%2Fa%2Fga%2Ful%2F545102302%2FECNS_Arns_prf.pdf">http://eegbulletinboard.com/groupee_files/attachments/4/4/5/445102302/445102302_ECNS_Arns_prf.pdf?ts=4A649D1A&amp;key=C5081747CE4E8F2F332A3BA00634C30A&amp;referrer=http%3A%2F%2Feegbulletinboard.com%2Feve%2Fforums%2Fa%2Fga%2Ful%2F545102302%2FECNS_Arns_prf.pdf</A></P><SPAN lang=FR style="COLOR: black; FONT-FAMILY: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: FR"><FONT size=3>
<P class=MsoNormal style="MARGIN: 0in 0in 10pt; TEXT-ALIGN: center; mso-line-height-alt: 9.45pt; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto" align=center><B><SPAN style="FONT-SIZE: 12pt; COLOR: black; FONT-FAMILY: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'">Efficacy of neurofeedback treatment in ADHD: The effects on inattention, impulsivity and hyperactivity: <BR>A meta-analysis.</SPAN></B><SPAN style="FONT-SIZE: 7pt; COLOR: black; FONT-FAMILY: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'"><?xml:namespace prefix = o ns = "urn:schemas-microsoft-com:office:office" /><o:p></o:p></SPAN></P></FONT></SPAN>
<P class=MsoNormal style="MARGIN: 0in 0in 0pt; TEXT-ALIGN: center; mso-line-height-alt: 9.45pt" align=center><SPAN lang=FR style="COLOR: black; FONT-FAMILY: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: FR"><FONT size=3>Martijn Arns<SUP> 1,2,*</SUP>, Sabine de Ridder<SUP> 2</SUP>, Ute Strehl<SUP> 3</SUP>, Marinus Breteler<SUP> 4, 5</SUP> &amp; Anton Coenen <SUP>5</SUP><o:p></o:p></FONT></SPAN></P>
<P class=MsoNormal style="MARGIN: 0in 0in 0pt; TEXT-ALIGN: justify; mso-line-height-alt: 9.45pt"><SPAN lang=FR style="COLOR: black; FONT-FAMILY: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: FR"><o:p><FONT size=3>&nbsp;</FONT></o:p></SPAN></P>
<P class=MsoNormal style="MARGIN: 0in 0in 0pt; TEXT-ALIGN: center; mso-line-height-alt: 9.45pt" align=center><SUP><SPAN lang=FR style="FONT-SIZE: 10pt; COLOR: black; FONT-FAMILY: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: FR">1 </SPAN></SUP><SPAN lang=EN-GB style="FONT-SIZE: 10pt; COLOR: black; FONT-FAMILY: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-GB">Brainclinics Diagnostics, Nijmegen, The Netherlands<o:p></o:p></SPAN></P>
<P class=MsoNormal style="MARGIN: 0in 0in 0pt; TEXT-ALIGN: center; mso-line-height-alt: 9.45pt" align=center><SUP><SPAN lang=FR style="FONT-SIZE: 10pt; COLOR: black; FONT-FAMILY: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: FR">2 </SPAN></SUP><SPAN lang=EN-GB style="FONT-SIZE: 10pt; COLOR: black; FONT-FAMILY: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-GB">Brainclinics Treatment, Nijmegen, The Netherlands<o:p></o:p></SPAN></P>
<P class=MsoNormal style="MARGIN: 0in 0in 0pt; TEXT-ALIGN: center; mso-line-height-alt: 9.45pt" align=center><SUP><SPAN lang=FR style="FONT-SIZE: 10pt; COLOR: black; FONT-FAMILY: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: FR">3 </SPAN></SUP><SPAN lang=EN-GB style="FONT-SIZE: 10pt; COLOR: black; FONT-FAMILY: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-GB">University of Tuebingen, Germany<o:p></o:p></SPAN></P>
<P class=MsoNormal style="MARGIN: 0in 0in 0pt; TEXT-ALIGN: center; mso-line-height-alt: 9.45pt" align=center><SUP><SPAN lang=FR style="FONT-SIZE: 10pt; COLOR: black; FONT-FAMILY: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: FR">4 </SPAN></SUP><SPAN lang=EN-GB style="FONT-SIZE: 10pt; COLOR: black; FONT-FAMILY: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-GB">EEG Resource Institute, Nijmegen, The Netherlands<o:p></o:p></SPAN></P>
<P class=MsoNormal style="MARGIN: 0in 0in 0pt; TEXT-ALIGN: center; mso-line-height-alt: 9.45pt" align=center><SUP><SPAN lang=FR style="FONT-SIZE: 10pt; COLOR: black; FONT-FAMILY: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: FR">5 </SPAN></SUP><SPAN lang=EN-GB style="FONT-SIZE: 10pt; COLOR: black; FONT-FAMILY: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-GB">Radboud University, Nijmegen, The Netherlands<o:p></o:p></SPAN></P>
<P class=MsoNormal style="MARGIN: 0in 0in 10pt; LINE-HEIGHT: 9.45pt; TEXT-ALIGN: justify; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto"><B><SPAN style="FONT-SIZE: 7pt; COLOR: black; FONT-FAMILY: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-size: 11.0pt">REFERENCE</SPAN></B><SPAN style="FONT-SIZE: 7pt; COLOR: black; FONT-FAMILY: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'"><BR>Efficacy of Neurofeedback treatment in ADHD: The effects on Inattention, Impulsivity and Hyperactivity: A meta-analysis (In Press). Martijn Arns, Sabine de Ridder, Ute Strehl, Marinus Breteler &amp; Anton Coenen. </SPAN><I><SPAN style="FONT-SIZE: 7pt; COLOR: black; FONT-FAMILY: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-size: 11.0pt">EEG and Clinical Neuroscience, 40: 180-189.</SPAN></I><SPAN style="FONT-SIZE: 7pt; COLOR: black; FONT-FAMILY: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'"><o:p></o:p></SPAN></P>
<P class=MsoNormal style="MARGIN: 0in 0in 10pt; LINE-HEIGHT: 9.45pt; TEXT-ALIGN: justify; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto"><B><SPAN style="FONT-SIZE: 7pt; COLOR: black; FONT-FAMILY: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-size: 11.0pt">ABSTRACT</SPAN></B><SPAN style="FONT-SIZE: 7pt; COLOR: black; FONT-FAMILY: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'"><BR>Since the first reports of neurofeedback treatment in ADHD in 1976 many studies have been carried out investigating the effects of neurofeedback on different symptoms of ADHD such as inattention, impulsivity and hyperactivity. This technique is also used by many practitioners, but the question as to the evidence-based level of this treatment is still unclear. In this study selected research on neurofeedback treatment for ADHD was collected and a meta-analysis was performed. <BR>Both prospective controlled studies and studies employing a pre- and post-design found large effect sizes (ES) for neurofeedback on impulsivity and inattention and a medium ES for hyperactivity. Randomized studies demonstrated a lower ES for hyperactivity suggesting that hyperactivity is probably most sensitive to non-specific treatment factors. <BR>Due to the inclusion of some very recent and sound methodological studies in this meta-analysis potential confounding factors such as small studies, lack of randomization in previous studies and a lack of adequate control groups have been addressed and the clinical effects of neurofeedback in the treatment of ADHD can be regarded as clinically meaningful. Three randomized studies have employed a semi-active control group which can be regarded as a credible sham control providing an equal level of cognitive training and client-therapist interaction. Therefore, in line with the AAPB and ISNR guidelines for rating clinical efficacy, we conclude that neurofeedback treatment for ADHD can be considered ‘Efficacious and Specific’ (Level 5) with a large ES for inattention and impulsivity and a medium ES for hyperactivity. <o:p></o:p></SPAN></P>
<P class=MsoNormal style="MARGIN: 0in 0in 10pt; LINE-HEIGHT: 9.45pt; TEXT-ALIGN: justify; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto"><SPAN style="FONT-SIZE: 7pt; COLOR: black; FONT-FAMILY: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'">&nbsp;<o:p></o:p></SPAN></P>
<P class=MsoNormal style="MARGIN: 0in 0in 10pt; LINE-HEIGHT: 9.45pt; TEXT-ALIGN: justify; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto"><I><SPAN style="FONT-SIZE: 7pt; COLOR: black; FONT-FAMILY: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-size: 11.0pt">Keywords: Neurofeedback, EEG Biofeedback, ADHD, meta-analysis, inattention, impulsivity, hyperactivity.</SPAN></I><SPAN style="FONT-SIZE: 7pt; COLOR: black; FONT-FAMILY: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'"><o:p></o:p></SPAN></P>
<P class=MsoNormal style="MARGIN: 0in 0in 10pt; LINE-HEIGHT: 9.45pt; TEXT-ALIGN: justify; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto"><B><I><SPAN style="FONT-SIZE: 7pt; COLOR: black; FONT-FAMILY: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-size: 11.0pt">Acknowledgement</SPAN></I></B><I><SPAN style="FONT-SIZE: 7pt; COLOR: black; FONT-FAMILY: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'"><BR></SPAN></I><I><SPAN style="FONT-SIZE: 7pt; COLOR: black; FONT-FAMILY: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-size: 11.0pt">We wish to acknowledge the following people for providing us with additional information for the meta-analysis : Hartmut Heinrich, Petra Studer, Jochen Kaiser, David Kaiser, Michael Linden, Johanne L&#233;vesque, Martin Holtmann, Ulrike Leins, Domenic Greco, Andr&#233; Achim, Genevi&#232;ve Moreau and Ali Reza Bakhshayesh. We also wish to acknowledge the support of Desiree Spronk in the preparation of this manuscript.</SPAN></I><SPAN style="FONT-SIZE: 7pt; COLOR: black; FONT-FAMILY: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'"><o:p></o:p></SPAN></P>
<P class=MsoNormal style="MARGIN: 0in 0in 10pt"><o:p><FONT face=Calibri size=3>&nbsp;</FONT></o:p></P>
eod;
require $site_root."/".$document_template_link;
@mysql_close($db);
?>